import os
import sys
import argparse
from datetime import datetime
from dotenv import load_dotenv
from notion_client import Client

# Load environment variables
load_dotenv()

class NotionContextManager:
    def __init__(self):
        self.notion_token = os.getenv("NOTION_API_TOKEN")
        if not self.notion_token:
            print("❌ Error: NOTION_API_TOKEN not found in .env")
            sys.exit(1)
        self.notion = Client(auth=self.notion_token)

    def parse_markdown_to_blocks(self, content):
        """Simple Markdown to Notion Blocks converter."""
        blocks = []
        for line in content.split('\n'):
            line = line.strip()
            if not line:
                continue
            
            if line.startswith('# '):
                blocks.append({
                    "object": "block",
                    "type": "heading_1",
                    "heading_1": {
                        "rich_text": [{"type": "text", "text": {"content": line[2:]}}]
                    }
                })
            elif line.startswith('## '):
                blocks.append({
                    "object": "block",
                    "type": "heading_2",
                    "heading_2": {
                        "rich_text": [{"type": "text", "text": {"content": line[3:]}}]
                    }
                })
            elif line.startswith('### '):
                blocks.append({
                    "object": "block",
                    "type": "heading_3",
                    "heading_3": {
                        "rich_text": [{"type": "text", "text": {"content": line[4:]}}]
                    }
                })
            elif line.startswith('- '):
                blocks.append({
                    "object": "block",
                    "type": "bulleted_list_item",
                    "bulleted_list_item": {
                        "rich_text": [{"type": "text", "text": {"content": line[2:]}}]
                    }
                })
            elif line.startswith('1. '):
                blocks.append({
                    "object": "block",
                    "type": "numbered_list_item",
                    "numbered_list_item": {
                        "rich_text": [{"type": "text", "text": {"content": line[3:]}}]
                    }
                })
            else:
                blocks.append({
                    "object": "block",
                    "type": "paragraph",
                    "paragraph": {
                        "rich_text": [{"type": "text", "text": {"content": line}}]
                    }
                })
        return blocks

    def create_context_entry(self, database_id, title, content_path=None, content_str=None, status="In Progress"):
        """Create a new entry in the Project Context database."""
        
        # Determine content source
        content = ""
        if content_path and os.path.exists(content_path):
            with open(content_path, 'r') as f:
                content = f.read()
        elif content_str:
            content = content_str
        else:
            print("❌ Error: No content provided")
            return None

        # Parse content into blocks
        children = self.parse_markdown_to_blocks(content)
        
        # Limit blocks to 100 for initial chunk (Notion API limit is 100 blocks per request)
        # For a robust solution, we would need to handle pagination, but for now we truncate or split.
        # Simple split: first 100 blocks.
        initial_children = children[:100]
        remaining_children = children[100:]

        try:
            properties = {
                "Phase": {"title": [{"text": {"content": title}}]},
                "Date": {"date": {"start": datetime.utcnow().strftime("%Y-%m-%d")}},
                "Status": {"select": {"name": status}},
                "Description": {"rich_text": [{"text": {"content": "Generated by Context Engineering Agent"}}]}
            }

            response = self.notion.pages.create(
                parent={"database_id": database_id},
                properties=properties,
                children=initial_children
            )
            print(f"✅ Success: Context entry created (URL: {response['url']})")
            
            # Append remaining blocks if any
            if remaining_children:
                page_id = response['id']
                self.append_children(page_id, remaining_children)
                
            return response
        except Exception as e:
            print(f"❌ Error creating Notion entry: {str(e)}")
            return None

    def append_children(self, page_id, children):
        """Append children to a page in chunks of 100."""
        chunk_size = 100
        for i in range(0, len(children), chunk_size):
            chunk = children[i:i + chunk_size]
            try:
                self.notion.blocks.children.append(block_id=page_id, children=chunk)
                print(f"  Append: Added {len(chunk)} blocks.")
            except Exception as e:
                print(f"❌ Error appending blocks: {str(e)}")

def main():
    parser = argparse.ArgumentParser(description="Notion Context Reporting")
    parser.add_argument("--db", required=True, help="Notion Database ID")
    parser.add_argument("--title", required=True, help="Entry Title")
    parser.add_argument("--file", help="Path to markdown file")
    parser.add_argument("--content", help="String content (fallback)")
    parser.add_argument("--status", default="In Progress", help="Status (e.g., In Progress, Done)")

    args = parser.parse_args()
    manager = NotionContextManager()
    
    manager.create_context_entry(
        database_id=args.db,
        title=args.title,
        content_path=args.file,
        content_str=args.content,
        status=args.status
    )

if __name__ == "__main__":
    main()
